### ISSUE TITLE
【0w】江南秋来黄叶飞，正是相逢好时节

### ISSUE THREAD

**Issue by hanlin0516** [hanlin0516/SH-RoundTable#1]
## 学而不厌

默而识之，学而不厌。朝闻道，夕死可矣。各位同侪于课程中所得，亦不止于写作。内在动机、主题阅读、最小行动……

而你时间不够落下了课程？似懂非懂还需要反刍？对同侪社群难舍难分？

——魔都学而组，在阅读中开出树来。
- 立足认知写作学课程，不断反刍，刻意练习
-  每周一篇千字文，输出倒逼输入，保持学习节奏
-  开智书单主题阅读，每周一本书，给脑中世界添砖加瓦。

主要根据地在澄子姐姐的书店（MeRead 普育西路105号8号楼107室）。每周一次。主持人由张沁@kunlunmao 、凋寒@HanLin0516 、蕙蕙@kirolan 、小宝@meepochen 、朱俊@SecZhujun 轮流担任。

社团小而精，八个小伙伴左右。长期输出是一场心智的角逐，内在动机极重要。超过8个小伙伴维护社群的成本大大增加。第一期活动预计10w。报名请抓紧~

——且慢，进门有门槛：
- 每周输出
-  成长型心智，乐于分享
-  魔都（非魔都同学可以参加线上活动）

---

本周为0W活动周，主持人： 凋寒  （场地待定，群内通知。）

请刷完预备周的六个卡包，一篇《红玫瑰白玫瑰》（张爱玲）的篇目，有余力的同学提交笔记。

9月24日 13：00-16：00 普育西路105号8号楼巴黎咖啡，期待大家到来~
- BP交流总结
- 故事训练：CLOSAT
-  分享交流 

江南秋来，黄叶纷飞。长风带爽，兴而高歌。正是相逢好时节。

---

看看魔都上次的活动~[【书店遇见你】上海线下活动 No. 1](https://github.com/OpenMindClub/Writer003/issues/225)

请fork仓库-[SH-Writing003](https://github.com/HanLin0516/SH-Writing003)

群二维码。入群解锁更多小伙伴~
![screenshot-wx2 qq com 2016-09-21 16-39-45](https://cloud.githubusercontent.com/assets/19284130/18703792/1211aa00-801a-11e6-8662-4b829dabff6b.png)

**Comment by Turbo-Snail** [comment]
CLOSAT游戏+[《权力游戏》番外](https://github.com/Turbo-Snail/SH-Writing003/blob/master/0w/assign.md)

**Comment by Cookman2019** [comment]
[写作练习＋卡包笔记](https://github.com/yanli-2016/SH-Writing003/tree/master/0w)
