### ISSUE TITLE
重复与韵律

### ISSUE THREAD

**Issue by hanlin0516** [hanlin0516/SH-RoundTable#14]
## 重复与韵律
* 框架
* 证据

## 项目小组成员

@凋寒
@陈颖

**Comment by hanlin0516** [comment]
你妈唠叨你会烦，老师讲课啰嗦你会烦，为什么小说里的重复就引人入胜？到底发生了什么？
* 重复是否读者所期待的
* 我目前的想法是随后探讨重复的不同面目
  * 诗歌的重复
  * 童话的重复（情节的重复）
  * 细节的重复
  * （这里最好再想一个，四个组块比较好看）
*  最后一个收束，不如写成轻松的评论体。我们俩互相评论阐发一下。

**Comment by haibeicy** [comment]
我目前有限的关于重复的想法

小说里的细节重复（对应你的细节重复这条）
- 作为链接：比如人物认识的原因，《家鸭和野鸭》里关键的人物的结识都是因为鲍勃迪伦的歌。
- 作为重要象征和线索：比如《白夜行》里的剪纸
- 作为主人公内心的象征：《生命清单》里的巴宝莉男，《白夜行》里的剪纸。（素材还不够，后期再丰富。目前能想到的。）

另外刚才想了下我提出的那个问题。
- 为什么会烦：重复的停留会让人厌倦，有利于塑造让人反感的情绪。唠叨啰嗦，换不同的方式讲同一件事情本质上都是停留。
- 为什么会好奇：完全没有关系的两件事情，如果场景中出现相同的事物，大脑会自动觉得有联系，然而对联系的实质不清楚，所以好奇的是联系的内容。所以在完全不想关的几件事情上留有相同的细节，有利于构建悬疑，引发读者继续读下去的愿望，写作的过程相当于作者设个题目，然后自己答题解题。
- 为什么会熟悉有亲切感：在事物发展的不同阶段或者不通场景，重复的细节让人有亲切感，但是此时的重复不是停留，背景和场景在变化，没有静止，所以重复的细节在读者心理上已经引起了相对运动，不是停留，所以不厌烦。

所以重复的效果讨厌不讨厌，是看是否引起思维和心理上的静止和运动。静止会讨厌，相对运动会让人留恋。
