### ISSUE TITLE
[180617]【圆桌谈】那些下酒菜…… 

### ISSUE THREAD

**Issue by hanlin0516** [hanlin0516/SH-RoundTable#15]
兴安餐厅，地靠黄陂南路地铁站，出地铁，过天桥。下了天桥，转过窄窄的小马路，梧桐树影盖着老房子，整个街道都是一种淡淡的烟火气。像是冬天刚出了第一笼包子的早点摊，热气腾出来，弥漫出来。不用特别去找，望见了兴安路的路牌，视线再往里一点，就能看见兴安餐厅的招牌。推开那道老式餐厅木门，棕色的油漆和金属门把，门里是另一个喧腾的世界……

**Comment by jason2960** [comment]
下午五点十分左右，我走出地铁站，穿过天桥，对着手机地图，寻寻觅觅，穿梭在淮海中路的弄堂里，来来回回，却迷失在喧嚣的闹市里。

无奈与星星通了电话，她发来了定位。我这才识图知返，一间不起眼的餐厅，推门而进，六七张圆桌子挤满了整个屋子，本就狭小的屋子更显局促。落座，点菜，闲聊，吃菜，畅聊，喝酒，碰杯，凉风……

大家坐在一起总是快乐的，不拘吃什么，聊什么。店家的菜可口，我们就着啤酒在隐喻的指引下行动，迷失在空间的迭代里。酒杯碰在一起，心里却溢出了欢喜。

**人行动瘫痪久了，就如生病了一般，是思想生了病。**

开智是治我们思想病的良药，良药苦口且不说，还需要有药影子，药效才能显现。你们是我的药影子。

写在后面：
这下我又有写的了，又想写了。该聊的，昨天晚上都伴着酒都聊的差不多了，待我写完故事，再续，哈哈。

**Comment by weiweilei** [comment]
大家都进步很快，这个复盘我写什么呢？
关于空间隐喻的新思考，还是其他？

早晨看到星星的翻译手册，觉得自己或许有可以有一些小分享。
当晚聊嗨，第二天早上醒了想起，唉呀，星星阿杰没时间分享翻译和写作的关系，太可惜哪。可没想到一早上就看到星星的翻译手册，受她的启发，觉得这次复盘或许有一点可以分享的内容了(大家都进步超快，可能我分享的，你们都已经在做了)。

纳博科夫说：写作的艺术首先应将这个世界视为潜在的小说来观察。

（个人被纳博科夫的洛丽塔里的感官细节捕获，一直好奇他是怎么创造出来的，直到看到文学讲稿里有其他人提到，洛丽塔书里面的细节是：“经过选择、分类，并且渗透全书的感知资料。”）

然后最近又在翻一本《从生活到小说》的书，开始思考自己是不是该多写写日记，由日记始，对生活素材进行一点再改造，练习写作能力，哪怕没有写作课，写作不是也可以一直继续下去了嘛。但真正行动，就是在圆桌聚会当天。

当晚去聚会坐的出租车，周围景色怡人，我自己呢，也心情愉悦。就这么一直由司机开着车儿（现在回想起来，当时是感觉出租车在河里游荡，驶向大家），车行驶在公路一刻，一个有意思的误会出现了，当时我感到眼睛余光有点异样，右侧高楼窗户似乎有点奇怪的事情发生（我居然感觉有一只小鸟在推开窗户），这种感觉非常微妙，于是我赶紧回头一看，其实是：一个人打开窗户在放拖把。 哈哈哈，我差点笑出声。
但这个有意思的瞬间，突然让我悟到了小说中原创的源泉——艺术源于生活，高于生活之类的balabala，公路上视角去看旁边的高楼，高楼上有小鸟推开窗户…… 这个视角和非常有戏剧性的瞬间激发了许多的想象。于是很多脑洞开始了：移动公交车上客人无意看到的凶杀案现场，目击证人看到一只猫推开了窗户………………  什么样的偶然会引起误会，误会到会出人命的地步呢，当这样去想的时候，会发现日常生活中，偶发的小事件，有趣之极。

之后，我在公交车上，迅速对前两天几个生活中的小事件进行了编造加记录的形式，我那真实又骗人的小日记：
第一个：酒店就在眼前，下车步行，也许就是两分钟的时间，可出租车司机还在绕绕弯弯，她一想到自己不能看到婚礼上新郎的“开场幸福表演”就隐隐恼火，她知道男友的新故事会像过去他们两人的故事一样，走向沉闷然后翻编然后死亡，这悲剧的开始时刻，她无论如何都想在场。
（真实素材是两件事的组合，揉一起加冲突）

第二个：卫生间的门把手小心翼翼地拧了几下，门似乎还是没锁上，他为自己的愚蠢感到尴尬 ，门外有自己的女朋友，他感觉自己像个小偷般谨慎，万一自己被女朋友发现自己是个乡巴佬了怎么办？

…………各种给自己加戏，只要有点感觉就要加些冲突对立，我果然是适合写撕扯型么？

**Comment by alissli** [comment]
### 前情摘要

寒那天说，这次是aliss组织的，aliss负责监督复盘完成。心下咯噔，升起不详预感，恐怕到最后，最不靠谱的，应该是我自己了。连续两天的面基，是有些累的，再加上一开始也没种下三次聚会都要复盘的种子，即便 是想写的，也停笔在那里，等一个心绪，等一个时机。甚至，在朋友圈灵感突现，写下：**不复盘的人生，堪比四处留情的宙斯。** 你应该不想做一个寡情薄意的男子吧？

 时效到期 ，到底是坑了【圆桌谈】与【信分线下】的复盘，回翻这句，倒有些心安理得做【宙斯】的快感。然而做一个男子的薄幸快感，没有抵过**我要写**的长情。此为又提笔故。

### 酒尽未醉，途遥不归

时间的流水冲刷，记忆一定是有些淡了，那就随它任意地流淌，回转在一个没有头绪的故事里吧。

（这个坑我得填上20180815补）
记忆经不起岁月的放大，寒说的空间的剧烈变形，也抵不过阿杰在旁边那吃吃地笑意，铭刻在心。那笑等于「我知道你写不出来」，不服气的脾气上来了，当时的我满怀壮志的接受了挑战。而前天线下，我们会心一笑，笑问对方是否决定认输，又不约而同再约交稿推迟一个月。一个月后，故事会逆转吗？who knows。时间会秀给你我看。

那一日的酒酣耳热，回到桌上，听闻阿杰得的考验是「以女孩子的口吻」写一个故事。我回答「可以啊，可以试试。」紧接着问「阿杰，为什么说我试着写百转千回的爱，你就忍不不住笑，而你以女孩子口吻写故事，我就没那种反应呢？」阿杰居然一下子愣住，低下头沉思起来。而这一低头的沉思，使我也惊讶起来，所以他真的是「不知道我知道他写不出，我也不会表现出来？」

那一夜，我们走出小饭店，夏夜的风，抚过皮肤，惬意之余还是惬意。寒说，我们应该吟诗。

是呵，酒酣既未醉，拍案畅谈时，何不配以诗文乎？只是我，还未及其技。看看前面的伙伴背影，我心想：总有一天可以的罢。

注：复兴公园游，阿杰说放弃挑战，2333。没有竞争的宇宙，很寂寞啊。

**Comment by alissli** [comment]
复盘到底是坑了些时日。圆桌再聚，凋寒仍未从帝都归来。那时思考过的问题：一群傻子聚在一起做事容易还是聪明人容易的答案，在这两个月里，慢慢去实践了。而这次缺了寒，却多了很多人的聚会，终究是告诉自己，圆桌终归是该归最初的圆桌。
