### ISSUE TITLE
【2w】快写慢改

### ISSUE THREAD

**Issue by kirolan** [hanlin0516/SH-RoundTable#4]
最小！最小！最小！
哪怕逻辑不通、文气不顺、陈词滥调、讲不好故事，都没关系，先写起来！从史上最烂版本开始，输出输出输出，你能看到自己的进步。

时间：
2016年10月4日 周二 下午2点－5点
建议带好笔记本，喜欢写字的带好纸笔

内容：
- 运用性感词汇，面朝大海、仰望星空、沙漠独行，从一句话、一个段落开始。学会用卡片写作，组合自己的拼图。快写内容随意。写好后可相互点评。
- 疑点讨论
- 故事训练CLOSAT

**Comment by SecZhujun** [comment]
[朱俊的CLOSAT：非洲民间故事——点石成金](https://github.com/SecZhujun/ZJ-Writing/blob/CLOSAT/CLOSAT4.md)

**Comment by SecZhujun** [comment]
【答案】第二讲第一关——看看你的远距离联想能力如何 ？
1、讨 
2、师
3、年
4、壮
5、操
6、响
7、居
8、集
9、善
10、理
11、鉴
12、存
13、配
14、程
15、见

其中3、9、10、14、15较难
