### ISSUE TITLE
【CLOSAT】玩法改善投票

### ISSUE THREAD

**Issue by SecZhujun** [hanlin0516/SH-RoundTable#9]
### 思路背景

整理CLOSAT故事时，我产生了两种情绪：
1、讲故事的时候记录卡片在多好啊
2、这个故事在讲什么呀，我不想写了
### 于是产生了几个想法：

保存卡片。张沁上次提到不必每次制作卡片，可以做一套成熟的卡片反复使用的想法，这时跳到我的眼前。拟采用最简单的方式——一个**四格盒子**
| 存放故事       | 人物卡、地点卡、物件卡   |
| 空白备用卡    |  入选精品卡片                   |

并且，每周投票选取好故事，半票及以上为通过，通过票选的好故事由朱俊同学自愿（积极地）倾情整理，发布到
### CLOSAT精选故事集

入选精选故事集的方式有两种：
1、当次线下成员投票，票数一半及以上。
2、投票没过没关系，故事所有者投稿到朱俊处即可。或整理后发布到当周issue作为作业。
### 游戏的奖惩机制

惩罚：评选当周最差故事，当选者下周多抽一张存档卡。
奖励：无（奖赏会伤人你不知道吗2333）
### 投票格式：

1、盒子收纳以往卡片 Y/N
2、故事精选               Y/N
3、奖惩机制               Y/N

**依次在评论中写下Y或者N表示投票，在相应的投票后给出不同意见。**

**Comment by SecZhujun** [comment]
作为提出者，我表示同意😊

**Comment by chenmingio** [comment]
支持1、2

**Comment by hanlin0516** [comment]
同意1，2，奖惩就算了，随心吧。

**Comment by kirolan** [comment]
同意1、2

**Comment by kunlunmao** [comment]
支持1、2
关于3，奖惩机制，我的看法是，惩罚就算了，
关于2，故事精选，每周的故事是否能够发布到简书等外部的平台上？形成集合和系列，应该会很有趣。
关于1，卡片，最好是形状统一，质感厚实的。刚在淘宝上面搜索“空白卡牌“，发现很多不错的很便宜的卡牌，可以自制哦。比如，白卡牌的背面，用不同色彩的字标注人物、事件、地点，在卡牌的正面写内容。当次用完的卡牌，收集到收纳盒中。一次一次积累，到以后可以打混了一起用。（再多YY一点，等形成一定量之后，可以考虑找喵设计一下，印刷一套。）
